Make slippi loggo do a barrel roll on hover
project-slippi/slippi-launcher pull request #218
Opened 2021-08-13 12:57 UTC by rapito

# It's quiet.. too quiet...
![giphy](https://user-images.githubusercontent.com/1380104/129359756-ac45cf1a-9c21-41c6-8f57-9eebe20f6370.gif)

https://user-images.githubusercontent.com/1380104/129359530-2b834eda-3f0a-4a93-b352-5510408d7142.mov

2021-08-14 01:56 UTC, vinceau commented
I love the idea but I don't love the implementation. Specifically this behaviour:

https://user-images.githubusercontent.com/8384734/129431044-9821caeb-16a6-41a1-8d01-662c0fb8b3ab.mov

2021-09-09 23:24 UTC, rapito commented
> I love the idea but I don't love the implementation. Specifically this behaviour:
> 
>  Screen.Recording.2021-08-14.at.11.50.11.am.mov

I refactored it to take a different approach.

2021-09-09 23:38 UTC, vinceau commented
> > I love the idea but I don't love the implementation. Specifically this behaviour:
> > Screen.Recording.2021-08-14.at.11.50.11.am.mov
> 
> I refactored it to take a different approach.

Does the new approach address the behaviour I mentioned before? If so, could you include in the PR a screengrab/video of the new behaviour when the mouse enters and leaves before the animation completes?

2021-09-10 19:43 UTC, rapito commented
> > > I love the idea but I don't love the implementation. Specifically this behaviour:
> > > Screen.Recording.2021-08-14.at.11.50.11.am.mov
> > 
> > 
> > I refactored it to take a different approach.
> 
> Does the new approach address the behaviour I mentioned before? If so, could you include in the PR a screengrab/video of the new behaviour when the mouse enters and leaves before the animation completes?

Yes:


https://user-images.githubusercontent.com/1380104/132908692-ca12479b-a782-4314-8bd1-68b5e6f1400c.mov

It only rolls once now though. And that's fine :)

2021-09-11 10:38 UTC, vinceau requested changes

2021-09-11 10:38 UTC, vinceau commented on src/renderer/components/BouncingSlippiLogo.tsx
> +  roll: boolean;
```suggestion
  animationState: "running" | "paused";
```
Maybe we can just pass the animation state in?

2021-09-11 10:38 UTC, vinceau commented on src/renderer/components/BouncingSlippiLogo.tsx
> +  animation-play-state: running, ${(props) => (props.roll ? "running" : "paused")};
```suggestion
  animation-play-state: running, ${(props) => props.animationState};
```

2021-09-11 10:38 UTC, vinceau commented on src/renderer/components/BouncingSlippiLogo.tsx
> +  // so we need to scale it down to avoid pivotal animations
```suggestion
```
I think I would prefer to keep comments outside of the `css` definition itself. If you want to comment maybe add it as javascript comments above the definition.

2021-09-12 13:49 UTC, rapito commented
There.

2021-09-12 23:26 UTC, vinceau approved these changes
LGTM

2021-09-12 23:26 UTC, merged