feat: add notice about OBS websocket update
project-slippi/slippi-launcher pull request #343
Opened 2022-09-29 03:04 UTC by NikhilNarayana

![image](https://user-images.githubusercontent.com/6331403/192929224-bebf2ec9-2b0a-40cd-852d-c584cc15bf5a.png)

uses localstorage to ensure it only shows once. this should help avoid users getting confused about the change.

2022-10-06 07:17 UTC, vinceau requested changes

2022-10-06 07:17 UTC, vinceau commented on src/renderer/containers/Console/index.tsx
> +const OBSWebsocketNotice = () => {
Can you move this into it's own component, and then within that same file/component just declare:

```typescript
const OBS_WEBSOCKET_NOTICE_KEY = "SEEN_OBS_WEBSOCKET_NOTICE";

// Inside the component
const [seenNotice, setSeenNotice] = React.useState<boolean>(localStorage.getItem(OBS_WEBSOCKET_NOTICE_KEY) === "true");
const onClose = () => {
  localStorage.setItem(OBS_WEBSOCKET_NOTICE_KEY, "true");
  setSeenNotice(true);
};
```

And then revert `useAdvancedUser` back to how it was? This local storage key is only ever going to be used within this component where as the other one is used in a few places.

2022-10-13 01:11 UTC, vinceau approved these changes

2022-10-13 01:16 UTC, vinceau approved these changes

2022-10-13 01:28 UTC, NikhilNarayana commented on src/renderer/containers/Console/OBSWebsocketNotice.tsx
> +  return (
works fine in testing. no visual or functional difference between returning and not returning null when seen.

2022-10-14 22:51 UTC, merged