Add player profile links to the replay browser
project-slippi/slippi-launcher pull request #450
Opened 2024-12-29 03:21 UTC by juebjueb

Follow up on PR #375 authored by [trstruth](https://github.com/project-slippi/slippi-launcher/pull/375#issue-1616061627).

![image](https://github.com/user-attachments/assets/9beae6f1-e3ca-4158-9cfb-9bce3f6a78b6)

Addressing comments from [vinceau](https://github.com/project-slippi/slippi-launcher/pull/375#issuecomment-1462981675):
> 1. The inconsistent behaviour of some badges being clickable and some not is quite jarring.
> 2. It occupies the badge click functionality in case we wanted to use that behaviour for something else in the future.
> 3. The `PlayerBadge` which should be a dumb component now also has to handle the click function which is undesirable. I'd rather leave that to the parent.

1. Added an explicit button to eliminate confusion for which badges are clickable.
2. I agree that a pop-up menu would be nice to allow further extension, but I worry this would be premature. There hasn't been much activity on the replay browser over the last year, and I wouldn't want there to be a menu that's only populated with one item for a long period of time.
3. Moved from PlayerBadge to its parent TeamElements

2025-03-15 18:22 UTC, erickaoek commented
This is awesome, someone review please :)

2025-04-10 22:23 UTC, JLaferri commented
I think this is cool and would be great to merge but I think the visual styling needs a little work. It's not awful but it certainly feels tacked on and like it doesn't fully belong. I'm not sure what my suggestion is to fix it atm though. I'm sure a designer could come up with a clean solution.

2025-04-20 02:24 UTC, juebjueb commented
Probably the visual issue is that the links are in between the player badges and the "vs". How about moving to the replay browser like so? Adds an extra click to get there, but looks nicer.

![image](https://github.com/user-attachments/assets/7223c2f1-b2a8-4682-9e57-4c596cedeb0b)

2025-04-20 05:55 UTC, JLaferri commented
> Probably the visual issue is that the links are in between the player badges and the "vs". How about moving to the replay browser like so? Adds an extra click to get there, but looks nicer.

I think I would personally be okay with that for now.

2025-04-20 11:22 UTC, juebjueb commented
Great, thanks! Ready for review.

2025-04-20 14:46 UTC, vinceau commented
what about moving the link to the actual connect code at the top of the replay stats page banner?

2025-04-20 15:46 UTC, juebjueb commented
We could, but this would have the same visual jank as the before where the links are in between the player names and the VS which breaks symmetry

2025-04-20 20:55 UTC, vinceau commented
> We could, but this would have the same visual jank as the before where the links are in between the player names and the VS which breaks symmetry

by links and visual symmetry are you referring to the external link visual indicator? because i was imagining not having that visual indicator and just having like an underline or something to indicate interactivity and clickable link. i don't see how that would break symmetry or have visual jank

2025-04-25 01:30 UTC, juebjueb commented
Done, see latest.

![image](https://github.com/user-attachments/assets/58ccc5e2-fc04-4d92-86af-986c49ad13d2)

2025-04-28 00:24 UTC, vinceau requested changes

2025-04-28 00:24 UTC, vinceau commented on src/renderer/pages/replays/replay_file_stats/player_info.tsx
> +              <div>{connectCode}</div>
```suggestion
              {connectCode}
```
can you remove the nested div here? we shouldn't need it.

2025-04-28 04:03 UTC, juebjueb commented
done

2025-05-12 12:27 UTC, merged